version: '3.8'

services:
  s_api_gateway:
    container_name: c_api_gateway
    image: ramizvaliyev/apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 9001:44384
    networks:
      - micro_net
      - int_net


  s_contact_api:
    container_name: c_contact_api
    image: ramizvaliyev/contactapi
    build:
      context: .
      dockerfile: Services/ContactApi/Contact.API/Dockerfile
    ports:
      - 9002:44386
    networks:
      - int_net

  s_reservation_api:
    container_name: c_reservation_api
    image: ramizvaliyev/reservationapi
    build:
      context: .
      dockerfile: Services/ResApi/Reservation.API/Dockerfile
    ports:
      - 9003:44385
    networks:
      - int_net
  
      




networks:
  int_net:
    internal: true
  micro_net:
    driver: bridge